import { ReactNode } from "react";
import Nav from "./nav.component";
import Head from "next/head";

type Props = {
  children?: ReactNode;
  title?: string;
};

const Layout = ({ children, title = "This is the default title" }: Props) => (
  <div>
    <Head>
      <title>{title}</title>
      <meta charSet="utf-8" />
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <header>
      <Nav />
    </header>
    {children}
    <footer>
      {/* <hr />
      <span>I am here to stay (Footer)</span> */}
    </footer>
  </div>
);

export default Layout;
